# Generated by Django 5.2.4 on 2026-04-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at',), 'verbose_name': 'проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
