from enum import Enum


class AvatarColor(str, Enum):
    BLUE = "#3B82F6"
    GREEN = "#16A34A"
    ORANGE = "#F59E0B"
    PINK = "#DB2777"
    SKY = "#0EA5E9"
    INDIGO = "#6366F1"
    RED = "#DC2626"
    EMERALD = "#059669"
    VIOLET = "#7C3AED"
    CYAN = "#0891B2"


SKILL_NAME_MAX_LENGTH = 124
USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256
PARTICIPANTS_PER_PAGE = 12
SKILLS_AUTOCOMPLETE_LIMIT = 10

AVATAR_PALETTE = tuple(color.value for color in AvatarColor)
AVATAR_HASH_BASE = 16
AVATAR_IMAGE_MODE = "RGB"
AVATAR_IMAGE_SIZE = (256, 256)
AVATAR_TEXT_POSITION = (AVATAR_IMAGE_SIZE[0] // 2, AVATAR_IMAGE_SIZE[1] // 2)
AVATAR_TEXTBOX_POSITION = (0, 0)
AVATAR_TEXT_COLOR = "white"
AVATAR_TEXT_ANCHOR = "mm"
AVATAR_FONT_NAME = "arial.ttf"
AVATAR_FONT_SIZE = 120
AVATAR_IMAGE_FORMAT = "PNG"
DEFAULT_AVATAR_INITIAL = "U"
